### ISSUE TITLE
[SUGGESTION] Quoting privacy setting

### ISSUE THREAD

**Issue by Aktimoose** [FireDiscordBot/bot#107]
**Is your feature request related to a problem? Please describe.**
I want to be able to cross server quote my friend's messages but they don't want their discord tag shown.

**Describe the solution you'd like**
A way to opt to have it so when your messages are quoted it does not show your username or avatar. It would also be useful if a server admin could opt an entire server out of having their messages quoted cross server, with or without the discord tag showing.

**Comment by GamingGeek** [comment]
I'm not sure I'd want to have webhooks tied to fire sending messages without any user attached due to the potential for abuse (e.g. users sending messages with inappropriate content, quoting it somewhere and having no link back to the original author)

Because of this, I won't be implementing this functionality
